export const BILL_FETCH_SUCCESS = 'BILL_FETCH_FAIL';
export const BILL_FETCH_FAIL = 'BILL_FETCH_FAIL';
export const DELETE_BILL_SUCCESS = 'DELETE_BILL_SUCCESS';
export const ADD_BILL_SUCCESS = 'ADD_BILL_SUCCESS';
export const PAYABLE_BILL_LIST_CREATED = 'PAYABLE_BILL_LIST_CREATED';
